### ISSUE TITLE
Have issues running on my RPI Homebridge

### ISSUE THREAD

**Issue by PnnnG** [vsternbach/homebridge-yeelight-ble#1]
**Describe Your Problem:**

Can't even get my Candelas mac. 
Have "Error scanning for devices" after pushing the SCAN button in plugins settings dialog, and the next strings in log...
Have installed it from Plugins tab of my HB UI.

**Logs:**

```json
[05/11/2023, 19:03:30] [Homebridge UI] [homebridge-yeelight-ble] Incoming Request: /scan
[05/11/2023, 19:03:30] [Homebridge UI] [homebridge-yeelight-ble] Error: Command failed: yeelightble scan -t 3 
/bin/sh: 1: yeelightble: not found

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'yeelightble scan -t 3 ',
  stdout: '',
  stderr: '/bin/sh: 1: yeelightble: not found\n'
}
[05/11/2023, 19:03:35] [Homebridge UI] [homebridge-yeelight-ble] Terminating child process...
[05/11/2023, 19:03:35] [Homebridge UI] [homebridge-yeelight-ble] Child process ended
[05/11/2023, 19:03:37] [Homebridge UI] Starting terminal session
```

**Plugin Config:**

```json
In screenshots
```

**Screenshots:**

![2023-11-05_19-03-54](https://github.com/vsternbach/homebridge-yeelight-ble/assets/124533121/a3e41b85-88b1-43bb-aaeb-9e6ce7925764)
![2023-11-05_19-10-39](https://github.com/vsternbach/homebridge-yeelight-ble/assets/124533121/be78580b-de40-4481-bcfd-13f2eb2e1dd2)
![2023-11-05_19-14-50](https://github.com/vsternbach/homebridge-yeelight-ble/assets/124533121/1c12bb1d-b687-4a19-9222-72ec5fdb6c0f)

**Environment:**

* **Plugin Version**: homebridge-yeelight-ble v2.2.0
* **Homebridge Version**:  [v1.7.0] ( but had the same with 1.6.x)
* **Node.js Version**: [v18.18.2]
* **NPM Version**: 9.8.1
* **Operating System**: Raspbian GNU/Linux Buster (10)

Thank you,
and I look forward for any support

**Comment by vsternbach** [comment]
The error is pretty much self-explanatory, you need to install python library yeelightble, refer to setup section in documentation

**Comment by PnnnG** [comment]
@vsternbach Thanks! I tried, but got:
```
pi@homebridge:/var/lib/homebridge $ sudo pip3 install git+https://github.com/vsternbach/yeelightble
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/vsternbach/yeelightble
  Cloning https://github.com/vsternbach/yeelightble to /tmp/pip-req-build-7128wn0q
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-7128wn0q/setup.py", line 2, in <module>
        from yeelightble.version import __version__
      File "/tmp/pip-req-build-7128wn0q/yeelightble/__init__.py", line 2, in <module>
        from .lamp import Lamp
      File "/tmp/pip-req-build-7128wn0q/yeelightble/lamp.py", line 5, in <module>
        from retry import retry
    ModuleNotFoundError: No module named 'retry'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-7128wn0q/
```
Meanwhile I found my Candela MAC with bluetoothctl, scan.

**Comment by vsternbach** [comment]
@PnnnG don't see your latest comment here, the thing with yeelightble installation is weird indeed, didn't have any problem installing it on rpi, but got the same error when trying to install it on my mac, modified something and hopefully it solves the problem, try reinstalling it

**Comment by PnnnG** [comment]
@vsternbach, I solved it! Installed py3, then yeelightble with all requires manually. And it works! Sometimes I see inverted status in Homebridge, but that is 99% better then nothing)
Thank you for this really crucial plugin for my smart home! I do love my candelas

**Comment by vsternbach** [comment]
Glad to hear the issue is resolved, and yeah ble connections are really unreliable and sometimes sending commands to the lamps just fails even with additional retries, so this is indeed the case where it's better than nothing :)
